server:
  port: 8080
  undertow:
    # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
    # 不要设置过大，如果过大，启动项目会报错：打开文件数过多
    io-threads: 8
    # 阻塞任务线程池, 当执行类似servlet请求阻塞IO操作, undertow会从这个线程池中取得线程
    # 它的值设置取决于系统线程执行任务的阻塞系数，默认值是IO线程数*8
    worker-threads: 64
    # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理
    # 每块buffer的空间大小,越小的空间被利用越充分，不要设置太大，以免影响其他应用，合适即可
    buffer-size: 1024
    # 是否分配的直接内存(NIO直接分配的堆外内存)
    direct-buffers: true

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3307/activ?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: 账号
    password: 密码
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  # redis 相关
  redis:
    #    password: 密码
    host: xxx.xxx.xxx.xxx
    database: 0
    port: 6379
    lettuce:
      pool:
        max-active: -1 # 连接池大连接数（使用负值表示没有限制）
        max-idle: 16 # 连接池中的大空闲连接
        min-idle: 4 # 连接池中的小空闲连接
        max-wait: 500 # 连接池大阻塞等待时间（使用负值表示没有限制）
        shutdown-timeout: 100   # 关闭超时时间

#  redis:
#    password: 密码
#    host: xxx.xxx.xxx.xxx
#    database: 0
#  redis:
#    password: 密码
#    sentinel:
#      master: mymaster
#      nodes: xxx.xxx.xxx.xxx:xxxx,xxx.xxx.xxx.xxx:xxxx,xxx.xxx.xxx.xxx:xxxx
#    jedis:
#      pool:
#        max-active: 8
#        max-idle: 8
#        max-wait: -1
#        min-idle: 0
#    database: 0

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  global-config:
    useActualParamName: true
    banner: false
    db-config:
      id-type: NONE
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: 1
      # 默认数据库表下划线命名
      table-underline: true
#  type-handlers-package: com.hmm.mht.activ.common.config


logging:
  #    config: classpath:log4j2-spring-dev.xml
  level:
    com.hmm.mht.activ.operation.dao: DEBUG
    com.hmm.mht: DEBUG

myswagger:
  version: @project.version@
  operation-path: http://127.0.0.1:8080
  notify-path: http://127.0.0.1:8080
  handle-path: http://127.0.0.1:8080
  shuffle-path: http://127.0.0.1:8080

mht-active: 1 #对应活动表id

#mht-active: #对应活动表id
#  - 1
#  - 2

#swagger:
#  enabled: false

# sms:
